name: Deploy Nginx HTML App Locally

on:
  push:
    branches:
      - main  # main branch me push hone par trigger

jobs:
  deploy:
    runs-on: self-hosted  # important: use self-hosted runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker Image
      run: |
        docker build -t html-nginx-app .

    - name: Stop Old Container
      run: |
        docker stop html-nginx-container || true
        docker rm html-nginx-container || true

    - name: Run Docker Container
      run: |
        docker run -d \
        --name html-nginx-container \
        -p 8085:80 \
        html-nginx-app
